{
"revision"=>
  [{"id"=>"69be1243a2bcfdb68cb136288f43d2fe", "name"=>"10-white-kitchens-ideas-White-kitchen-with-red-worktops.jpg", "basename"=>"10-white-kitchens-ideas-White-kitchen-with-red-worktops", "ext"=>"jpg", "size"=>11979, "mime"=>"image/jpeg", "type"=>"image", "field"=>nil, "original_id"=>"31b82484ba563c646cfd7800fe92fdfc", "url"=>"http://potoschool-dev.s3.amazonaws.com/69/be1243a2bcfdb68cb136288f43d2fe/10-white-kitchens-ideas-White-kitchen-with-red-worktops.jpg", "meta"=>{"width"=>160, "height"=>160, "date_recorded"=>nil, "date_file_created"=>nil, "date_file_modified"=>"2012/04/10 15:54:02 GMT", "title"=>nil, "description"=>nil, "location"=>nil, "city"=>nil, "state"=>nil, "country"=>nil, "country_code"=>nil, "keywords"=>nil, "aperture"=>nil, "exposure_compensation"=>nil, "exposure_mode"=>nil, "exposure_time"=>nil, "flash"=>nil, "focal_length"=>nil, "f_number"=>nil, "iso"=>nil, "light_value"=>nil, "metering_mode"=>nil, "shutter_speed"=>nil, "white_balance"=>nil, "device_name"=>nil, "device_vendor"=>nil, "device_software"=>nil, "latitude"=>nil, "longitude"=>nil, "orientation"=>nil, "frame_count"=>nil}}], 
"index"=>[{"id"=>"489305e4b80a048421a144a00559797a", "name"=>"10-white-kitchens-ideas-White-kitchen-with-red-worktops.jpg", "basename"=>"10-white-kitchens-ideas-White-kitchen-with-red-worktops", "ext"=>"jpg",
   "size"=>25703, "mime"=>"image/jpeg", "type"=>"image", "field"=>nil, "original_id"=>"31b82484ba563c646cfd7800fe92fdfc", 
    "url"=>"http://potoschool-dev.s3.amazonaws.com/48/9305e4b80a048421a144a00559797a/10-white-kitchens-ideas-White-kitchen-with-red-worktops.jpg", 
    "meta"=>{"width"=>260, "height"=>260, "date_recorded"=>nil, "date_file_created"=>nil, "date_file_modified"=>"2012/04/10 15:54:02 GMT", "title"=>nil, "description"=>nil, "location"=>nil, "city"=>nil, "state"=>nil, "country"=>nil, "country_code"=>nil, "keywords"=>nil, "aperture"=>nil, "exposure_compensation"=>nil, "exposure_mode"=>nil, "exposure_time"=>nil, "flash"=>nil, "focal_length"=>nil, "f_number"=>nil, "iso"=>nil, "light_value"=>nil, "metering_mode"=>nil, "shutter_speed"=>nil, "white_balance"=>nil, "device_name"=>nil, "device_vendor"=>nil, "device_software"=>nil, "latitude"=>nil, "longitude"=>nil, "orientation"=>nil, "frame_count"=>nil}}], 
"display"=>[{"id"=>"65fb3cea3b89fe4331654cbda9d77685", "name"=>"10-white-kitchens-ideas-White-kitchen-with-red-worktops.jpg", "basename"=>"10-white-kitchens-ideas-White-kitchen-with-red-worktops", "ext"=>"jpg", "size"=>86548, "mime"=>"image/jpeg", "type"=>"image", "field"=>nil, "original_id"=>"31b82484ba563c646cfd7800fe92fdfc", "url"=>"http://potoschool-dev.s3.amazonaws.com/65/fb3cea3b89fe4331654cbda9d77685/10-white-kitchens-ideas-White-kitchen-with-red-worktops.jpg", "meta"=>{"width"=>590, "height"=>590, "date_recorded"=>nil, "date_file_created"=>nil, "date_file_modified"=>"2012/04/10 15:54:02 GMT", "title"=>nil, "description"=>nil, "location"=>nil, "city"=>nil, "state"=>nil, "country"=>nil, "country_code"=>nil, "keywords"=>nil, "aperture"=>nil, "exposure_compensation"=>nil, "exposure_mode"=>nil, "exposure_time"=>nil, "flash"=>nil, "focal_length"=>nil, "f_number"=>nil, "iso"=>nil, "light_value"=>nil, "metering_mode"=>nil, "shutter_speed"=>nil, "white_balance"=>nil, "device_name"=>nil, "device_vendor"=>nil, "device_software"=>nil, "latitude"=>nil, "longitude"=>nil, "orientation"=>nil, "frame_count"=>nil}}]}
The result is 
